### ISSUE TITLE
Blockchain Explorer - 022 - Get data from a red flag

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#449]
Check : 

- [x] [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0) 最新內容更新到此單子敘述
- [x] done / commit / PR

Todo : 
- [x] Update 022 API document ([API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0))

--- 

## 022 - Get data from a red flag

HTTP Request: `GET /app/red_flags/:red_flag_id`

Parameters: none

Request Example: `GET /app/red_flags/140050038`

Response Example:

```json
{
  "id": "140050038",
  "chainId": "usdt",
  "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
  "createdTimestamp": 1686579200,
  "interactedAddresses": [
    {
      "id": "122134",
      "chainId": "eth"
    },
    {
      "id": "134325",
      "chainId": "usdt"
    }
  ],
  "totalAmount": 100,
  "unit": "USDT",
  "transactionHistoryData": [
    {
      "id": "918402",
      "chainId": "btc",
      "createdTimestamp": 1686579229,
      "from": [{ "type": "address", "address": "912299" }],
      "to": [{ "type": "contract", "address": "110132" }],
      "status": "SUCCESS"
    },
    {
      "id": "912299",
      "chainId": "btc",
      "createdTimestamp": 1687860718,
      "from": [{ "type": "address", "address": "110132" }],
      "to": [{ "type": "contract", "address": "310683" }],
      "status": "PENDING"
    }
    //...
  ]
}
```

**Comment by godmmt** [comment]
## 022 - Get data from a red flag

HTTP Request: `GET /app/red_flags/:red_flag_id`

Parameters: none

Request Example: `GET /app/red_flags/140050038`

Response Example:

```json
{
  "id": "140050038",
  "chainId": "usdt",
  "chainIcon": "/currencies/usdt.svg",
  "addressId": "140052",
  "address": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
  "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
  "createdTimestamp": 1686579200,
  "interactedAddresses": [
    {
      "id": "122134",
      "chainId": "eth"
    },
    {
      "id": "134325",
      "chainId": "usdt"
    }
  ],
  "totalAmount": 100,
  "unit": "USDT",
  "transactionHistoryData": [
    {
      "id": "918402",
      "chainId": "btc",
      "createdTimestamp": 1686579229,
      "from": [{ "type": "address", "address": "912299" }],
      "to": [{ "type": "contract", "address": "110132" }],
      "status": "SUCCESS"
    },
    {
      "id": "912299",
      "chainId": "btc",
      "createdTimestamp": 1687860718,
      "from": [{ "type": "address", "address": "110132" }],
      "to": [{ "type": "contract", "address": "310683" }],
      "status": "PENDING"
    }
    //...
  ]
}
```

**Comment by godmmt** [comment]
## Knowing Prisma:

- [ ] Read [prisma/README.md](https://github.com/prisma/prisma/blob/main/README.md)
- [ ] Practice [Start from scratch](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch)
- [ ] Practice [Quickstart](https://www.prisma.io/docs/getting-started/quickstart)

**Comment by godmmt** [comment]
took 5.5 hours

50% finished.

remain 1 hour

**Comment by godmmt** [comment]
# 補充 : if schema.prisma updated
### Reference : [Prisma Development and production](https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production)

### Development environments
In a development environment, use the migrate dev command to generate and apply migrations:

```bash
npx prisma migrate dev 
```

Create and apply migrations
> migrate dev is a development command and should never be used in a production environment.

This command:

1. Reruns the existing migration history in the [shadow database](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database) in order to detect schema drift (edited or deleted migration file, or a manual changes to the database schema)
2. Applies pending migrations to the shadow database (for example, new migrations created by colleagues)
3. If it detects changes to the Prisma schema, it generates a new migration from these changes
4. Applies all unapplied migrations to the development database and updates the _prisma_migrations table
5. Triggers the generation of artifacts (for example, Prisma Client)

The migrate dev command will prompt you to reset the database in the following scenarios:
- Migration history conflicts caused by [modified or missing migrations](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/migration-histories#do-not-edit-or-delete-migrations-that-have-been-applied)
- The database schema has drifted away from the end-state of the migration history

**Comment by godmmt** [comment]
## 022 - Get data from a red flag

HTTP Request: `GET /app/red_flags/:red_flag_id`

Parameters: none

Request Example: `GET /app/red_flags/140050038`

Response Example:

```json
{
  "id": "140050038",
  "chainId": "usdt",
  "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
  "createdTimestamp": 1686579200,
  "interactedAddresses": [
    {
      "id": "122134",
      "chainId": "eth"
    },
    {
      "id": "134325",
      "chainId": "usdt"
    }
  ],
  "totalAmount": 100,
  "unit": "USDT",
  "transactionHistoryData": [
    {
      "id": "918402",
      "chainId": "btc",
      "createdTimestamp": 1686579229,
      "from": [{ "type": "address", "address": "912299" }],
      "to": [{ "type": "contract", "address": "110132" }],
      "status": "SUCCESS"
    },
    {
      "id": "912299",
      "chainId": "btc",
      "createdTimestamp": 1687860718,
      "from": [{ "type": "address", "address": "110132" }],
      "to": [{ "type": "contract", "address": "310683" }],
      "status": "PENDING"
    }
    //...
  ]
}
```

**Comment by godmmt** [comment]
# Note
1. API type 定義改成與前端共同使用同一個 interface
2. 記得將 022 API document 要修改一致
3. 前端畫面需要有資料找不到的畫面
4. 注意 URL 參數 (red_flag_id) 傳入是字串，要轉換成 Int
    ```ts
    // Info: (20240131 - Liz) 解構 URL 參數，並將字串轉換成數字
    const red_flag_id = parseInt(req.query.red_flag_id as string, 10);
    
    // Info: (20240131 - Liz) 若 URL 參數沒有成功轉換成數字，回傳 400
    if (Number.isNaN(red_flag_id)) {
      res.status(400).send('400 - typeof red_flag_id must be Number');
      return;
    }
    ```

**Comment by godmmt** [comment]
took 13 hours

done.

API v1.1.0 Updated Ver : [2e1f72e](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0/2e1f72e7e9bb742442e616be4ba632d7d5fd1dc1)

**Comment by godmmt** [comment]
- [ ] 畫面調整 #575
